scriptStack = [
    "cycle B",
    "eject SAFE",
    "grab 5",
    "cycle E",
    "eject SAFE",
    "grab 1",
    "cycle A",
    "eject SAFE",
    "grab 3",
    "grab 7",
    "grab 6",
    "cycle D",
    "eject SAFE",
    "grab 11",
    "cycle G",
    "eject SAFE",
    "grab 13",
    "grab 10",
    "cycle H",
    "eject SAFE",
    "grab 14",
    "cycle I",
    "eject SAFE",
    "grab 12",
    "grab 8",
    "grab 9",
    "cycle F",
    "eject SAFE",
    "grab 4",
    "grab 2",
    "cycle C",
    "park",
]