// autogenerated at 1624511315
void driverSkills(void) {
  // ----------------
  // cycle B
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  driveInches(0.5);
  cvCycle();
  driveInches(-12);
  // ----------------
  // eject SAFE
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  ejectAll();
  // ----------------
  // grab 5
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  turnDegrees(-180.023);
  driveInches(26.0);
  cvIntake();
  // ----------------
  // cycle E
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  driveInches(12.0);
  cvCycle();
  driveInches(-12);
  // ----------------
  // eject SAFE
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  ejectAll();
  // ----------------
  // grab 1
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  turnDegrees(143.125);
  driveInches(42.0);
  cvIntake();
  // ----------------
  // cycle A
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  turnDegrees(-21.142);
  driveInches(25.736);
  cvCycle();
  driveInches(-12);
  // ----------------
  // eject SAFE
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  ejectAll();
  // ----------------
  // grab 3
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  turnDegrees(-121.983);
  driveInches(14.0);
  cvIntake();
  // ----------------
  // grab 7
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  turnDegrees(-50.707);
  driveInches(38.851);
  cvIntake();
  // ----------------
  // grab 6
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  turnDegrees(140.718);
  driveInches(6.0);
  cvIntake();
  // ----------------
  // cycle D
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  driveInches(8.0);
  cvCycle();
  driveInches(-12);
  // ----------------
  // eject SAFE
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  ejectAll();
  // ----------------
  // grab 11
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  turnDegrees(146.849);
  driveInches(106.258);
  cvIntake();
  // ----------------
  // cycle G
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  turnDegrees(160.6);
  driveInches(159.207);
  cvCycle();
  driveInches(-12);
  // ----------------
  // eject SAFE
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  ejectAll();
  // ----------------
  // grab 13
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  turnDegrees(-159.397);
  driveInches(19.736);
  cvIntake();
  // ----------------
  // grab 10
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  turnDegrees(-1.662);
  driveInches(25.267);
  cvIntake();
  // ----------------
  // cycle H
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  turnDegrees(123.702);
  driveInches(32.0);
  cvCycle();
  driveInches(-12);
  // ----------------
  // eject SAFE
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  ejectAll();
  // ----------------
  // grab 14
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  turnDegrees(-131.608);
  driveInches(30.166);
  cvIntake();
  // ----------------
  // cycle I
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  turnDegrees(86.631);
  driveInches(33.255);
  cvCycle();
  driveInches(-12);
  // ----------------
  // eject SAFE
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  ejectAll();
  // ----------------
  // grab 12
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  turnDegrees(-142.151);
  driveInches(14.249);
  cvIntake();
  // ----------------
  // grab 8
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  turnDegrees(-40.909);
  driveInches(35.814);
  cvIntake();
  // ----------------
  // grab 9
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  turnDegrees(138.026);
  driveInches(6.0);
  cvIntake();
  // ----------------
  // cycle F
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  driveInches(8.0);
  cvCycle();
  driveInches(-12);
  // ----------------
  // eject SAFE
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  ejectAll();
  // ----------------
  // grab 4
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  turnDegrees(-90.012);
  driveInches(18.0);
  cvIntake();
  // ----------------
  // grab 2
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  turnDegrees(-69.442);
  driveInches(16.176);
  cvIntake();
  // ----------------
  // cycle C
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  turnDegrees(127.426);
  driveInches(25.736);
  cvCycle();
  driveInches(-12);
  // ----------------
  // park
  
  // DEV CONTROLS
  pros::delay(1000);
 // DEV CONTROLS

  driveInches(-24.0);
  stopAll();
  return;
}
