// autogenerated at 1624476175
void driverSkills(void) {
  // WARNING: generated with errors.
  // cycle B
  driveInches(0.5);
  cvCycle();
  driveInches(-12);
  // eject SAFE
  // grab 5
  turnDegrees(-180.023);
  driveInches(26.0);
  cvIntake();
  // cycle E
  driveInches(12.0);
  cvCycle();
  driveInches(-12);
  // eject SAFE
  // grab 1
  turnDegrees(143.125);
  driveInches(42.0);
  cvIntake();
  // cycle A
  turnDegrees(-21.142);
  driveInches(25.736);
  cvCycle();
  driveInches(-12);
  // eject SAFE
  // grab 3
  turnDegrees(-121.983);
  driveInches(14.0);
  cvIntake();
  // grab 7
  turnDegrees(-50.707);
  driveInches(38.851);
  cvIntake();
  // grab 6
  turnDegrees(140.718);
  driveInches(6.0);
  cvIntake();
  // cycle D
  driveInches(8.0);
  cvCycle();
  driveInches(-12);
  // eject SAFE
  // grab 11
  turnDegrees(146.849);
  driveInches(106.258);
  cvIntake();
  // cycle G
  turnDegrees(160.6);
  driveInches(159.207);
  cvCycle();
  driveInches(-12);
  // eject SAFE
  // grab 13
  turnDegrees(-159.397);
  driveInches(19.736);
  cvIntake();
  // grab 10
  turnDegrees(-1.662);
  driveInches(25.267);
  cvIntake();
  // cycle H
  turnDegrees(123.702);
  driveInches(32.0);
  cvCycle();
  driveInches(-12);
  // eject SAFE
  // grab 14
  turnDegrees(-131.608);
  driveInches(30.166);
  cvIntake();
  // cycle I
  turnDegrees(86.631);
  driveInches(33.255);
  cvCycle();
  driveInches(-12);
  // eject SAFE
  // grab 12
  turnDegrees(-142.151);
  driveInches(14.249);
  cvIntake();
  // grab 8
  turnDegrees(-40.909);
  driveInches(35.814);
  cvIntake();
  // grab 9
  turnDegrees(138.026);
  driveInches(6.0);
  cvIntake();
  // cycle F
  driveInches(8.0);
  cvCycle();
  driveInches(-12);
  // eject SAFE
  // grab 4
  turnDegrees(-90.012);
  driveInches(18.0);
  cvIntake();
  // grab 2
  turnDegrees(-69.442);
  driveInches(16.176);
  cvIntake();
  // cycle C
  turnDegrees(127.426);
  driveInches(25.736);
  cvCycle();
  driveInches(-12);
  // park
  driveInches(-24.0);
  stopAll(); return;
  // WARNING: generated with errors.
}
