#define PORT_UNKNOWN 30

#define LEFT_DRIVE_MOTOR_1_PORT 2
#define LEFT_DRIVE_MOTOR_2_PORT 4
#define LEFT_DRIVE_MOTOR_3_PORT 3

#define RIGHT_DRIVE_MOTOR_1_PORT 14
#define RIGHT_DRIVE_MOTOR_2_PORT 13
#define RIGHT_DRIVE_MOTOR_3_PORT 12

#define LEFT_INTAKE_MOTOR_PORT 5
#define RIGHT_INTAKE_MOTOR_PORT 15

#define MIDDLE_ROLLER_MOTOR_1_PORT 17
#define MIDDLE_ROLLER_MOTOR_2_PORT 18
#define TOP_ROLLER_MOTOR_PORT 8

#define IMU_PORT 19

#define CONTROLLER_THRESHOLD 20